"""Predictor: the public face of the engine.

Input: two player names + surface.
Output: structured JSON. The probability comes from Elo alone
("math judges"). Evidence is attached for the narrator and for
any agent on the other end of an A2A call.
"""

from __future__ import annotations

import sqlite3
from functools import lru_cache

import sqlite3 as _sq

from glicko2 import Glicko2Engine
from evidence import find_player, gather, match_level
from paths import DB as DB_PATH

_engines: dict = {}


def engine(tour: str = "ATP"):
    """Replay once per process per tour (ATP ~380k rows, WTA ~680k)."""
    if tour not in _engines:
        eng = Glicko2Engine()
        con = _sq.connect(DB_PATH)
        q = """SELECT tourney_date, surface, winner_id, loser_id
               FROM matches WHERE winner_id IS NOT NULL AND tour=?
               AND tourney_level != 'D'
               ORDER BY tourney_date, tourney_id, match_num"""
        for date, surface, wid, lid in con.execute(q, (tour,)):
            eng.update(wid, lid, surface or "", date)
        con.close()
        _engines[tour] = eng
    return _engines[tour]


def predict(player_a: str, player_b: str, surface: str = "Hard",
            tour: str = "ATP", db_path: str = DB_PATH) -> dict:
    surface = surface.capitalize()
    if surface not in ("Hard", "Clay", "Grass", "Carpet"):
        return {"error": f"unknown surface '{surface}'"}

    tour = tour.upper()
    if tour not in ("ATP", "WTA"):
        return {"error": f"unknown tour '{tour}' (ATP or WTA)"}
    con = sqlite3.connect(db_path)
    con.execute("PRAGMA case_sensitive_like=OFF")
    ra = find_player(con, player_a, tour)
    rb = find_player(con, player_b, tour)
    if not ra or not rb:
        missing = player_a if not ra else player_b
        con.close()
        return {"error": f"player not found in database: '{missing}'"}

    (aid, aname), (bid, bname) = ra, rb
    eng = engine(tour)
    p_a = eng.predict(aid, bid, surface)
    ev = gather(con, aid, bid, surface)
    level = match_level(con, aid, bid)
    con.close()

    sa, sb = eng.players[aid], eng.players[bid]
    result = {
        "match": f"{aname} vs {bname}",
        "tour": tour,
        "level": level,
        "surface": surface,
        "predicted_winner": aname if p_a >= 0.5 else bname,
        "win_probability": round(max(p_a, 1 - p_a), 3),
        "probability_a": round(p_a, 3),
        "method": ("surface-adjusted Glicko-2 (deterministic); trained on "
                   "tour + Challenger/ITF matches from 2000; benchmarked vs "
                   "closing odds: ATP 65.4% (market 67.9%), "
                   "WTA 65.7% (market 67.2%)"),
        "ratings": {
            aname: {"overall": round(sa.overall.rating),
                    "uncertainty": round(sa.overall.rd),
                    surface: round(sa.by_surface[surface].rating)},
            bname: {"overall": round(sb.overall.rating),
                    "uncertainty": round(sb.overall.rd),
                    surface: round(sb.by_surface[surface].rating)},
        },
        "evidence": ev,
        "caveats": _caveats(sa, sb, surface, ev, level),
        "data_through": _data_through(db_path, tour),
    }
    return result


def _data_through(db_path: str, tour: str) -> str:
    """Newest match in the database for this tour, as YYYY-MM-DD."""
    con = _sq.connect(db_path)
    row = con.execute(
        "SELECT MAX(tourney_date) FROM matches WHERE tour=?", (tour,)).fetchone()
    con.close()
    d = row[0] if row else None
    return f"{d // 10000:04d}-{(d // 100) % 100:02d}-{d % 100:02d}" if d else "unknown"


# Rating uncertainty is structurally higher at lower tiers (measured mean
# RD: tour ~77, challenger ~98, ITF ~110), so a fixed threshold would fire
# on nearly every lower-tier request and stop meaning anything.
RD_THRESHOLD = {"tour": 100, "challenger": 130, "itf": 150, "unknown": 120}
RD_SURFACE_THRESHOLD = {"tour": 150, "challenger": 180, "itf": 200,
                        "unknown": 170}


def _caveats(sa, sb, surface, ev, level: str = "tour") -> list[str]:
    """Honest uncertainty flags, generated by rules not vibes."""
    out = []
    rd_lim = RD_THRESHOLD.get(level, 100)
    surf_lim = RD_SURFACE_THRESHOLD.get(level, 150)
    for st, name_key in ((sa, "a"), (sb, "b")):
        if st.overall.rd > rd_lim:
            out.append(f"player_{name_key} rating uncertainty is high "
                       f"(RD {st.overall.rd:.0f}); few recent matches or long absence")
        if st.by_surface[surface].rd > surf_lim:
            out.append(f"player_{name_key} {surface} rating is weakly established "
                       f"(RD {st.by_surface[surface].rd:.0f})")
        rest = ev.get(f"rest_days_{name_key}")
        if rest is not None and rest > 60:
            out.append(f"player_{name_key} has no recorded match in {rest} days; "
                       f"injury/absence unknown to this system")
    if level == "itf":
        out.append("ITF level: bookmakers do not price these matches, so no "
                   "market check exists on this number")
    out.append("no injury, weather, or draw context: ratings end at the data cutoff")
    return out


if __name__ == "__main__":
    import json
    import sys

    a = sys.argv[1] if len(sys.argv) > 1 else "Carlos Alcaraz"
    b = sys.argv[2] if len(sys.argv) > 2 else "Jannik Sinner"
    s = sys.argv[3] if len(sys.argv) > 3 else "Clay"
    t = sys.argv[4] if len(sys.argv) > 4 else "ATP"
    print(json.dumps(predict(a, b, s, t), indent=2))
